CREATE DATABASE IF NOT EXISTS `PesceMuccaBot` DEFAULT CHARACTER SET utf8;
USE `PesceMuccaBot`;

DROP TABLE IF EXISTS `Admins`;
CREATE TABLE IF NOT EXISTS `Admins` (
  `id` BIGINT,
  `first_name` TEXT DEFAULT NULL,
  `last_name` TEXT DEFAULT NULL,
  `username` VARCHAR(32) UNIQUE DEFAULT NULL,
  `phone_number` TEXT DEFAULT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8;
